### PR TITLE
Compute webmercator resolution with full accuracy

### LINKED ISSUE #241: Full accuracy webmercator extents
The actual value of the webmercator equatorial circumference (used for tiling) is based on the value 6378137 for the Earth radiut (taken from the semimajor axis of WGS84’s ellipsoid). So, the size of the level 0 tile (2·R·PI) should be more accurately computed as 40075016.68557849 (current value is 40075017.0).

We should replace the definition of [CDB_XYZ_Resolution](https://github.com/CartoDB/cartodb-postgresql/blob/897689dd439e40256c4a66d02d78a7f31eaaf012/scripts-available/CDB_XYZ.sql#L9) with `SELECT 6378137.0*2.0*pi() / 256.0 / power(2.0, z);`  to get maximum accuracy of tile/pixel coordinates.

This will make the resolution values consistent with those used in the tiler:
https://github.com/CartoDB/tilelive-mapnik/blob/d04792444eb356d1e240ecd792f5d0ab933b213e/lib/render.js#L7

### PR DESCRIPTION
**Pull request by jgoizueta**
Fixes #241

### CODE REVIEW

**Comment by jgoizueta** [comment]
Please review @rafatower

**Comment by rafatower** [comment]
okay, but two questions:
- how this affects actual calculations? I mean, the pixel resolution is not the same in both axis, so an error is granted depending on the zoom level, right? (from my ignorance).
- have you tested what happens with the IMMUTABLE modifier when you update the extension? Will it actually take the newest, more accurate version of the function's results?

**Comment by jgoizueta** [comment]
Basically we're adding a small (irrelevant for current applications) bun unnecessary error to the inevitable error due to floating point's limited precision. Not a big deal, but this makes the exact values computed inconsistent with those used in the tiler: https://github.com/CartoDB/tilelive-mapnik/blob/d04792444eb356d1e240ecd792f5d0ab933b213e/lib/render.js#L7

Regarding the immutability, I've checked that when the function is replaced the new values are used (even for z values previously computed)

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
