### PR TITLE
PR for 0.8.1 release

### PR DESCRIPTION
**Pull request by pramsey**

### CODE REVIEW

**Comment by pramsey** [comment]
Hm, the QuotaInBytes test seems to be non-deterministic too. Werks fer me at home, failed once on Travis, passed a second time in a different test run.

**Comment by pramsey** [comment]
Bump @javisantana @rochoa, this is causing issues for both FME and OGR users trying to work w/ SQL API (also known as "enterprise users") it needs to get rolled out on a pretty high priority.

**Comment by javisantana** [comment]
looks good, you can merge it.

Could we deploy this tomorrow @rafatower

**Comment by rochoa** [comment]
Hey... but where is the fix for cdb_usertables?

**Comment by rochoa** [comment]
Oh, I see it here: https://github.com/CartoDB/cartodb-postgresql/commit/734561de4cbe44b3713f5f13713a6114cbd4c2e2

**Comment by pramsey** [comment]
I, er, cowboy'ed it onto master already... *shame*

**Comment by rochoa** [comment]
Hehe, fair enough.

**Comment by GarbageBear** [comment]
Thank you for this fix. It does seem to address the recently introduced issue.

**Pull request merged**
