### PR TITLE
Adding function to produce a great circle between two points.

### PR DESCRIPTION
**Pull request by stuartlynn**
Adding a function here to quickly create great circles between two points. Format is CDB_GreatCircle(start,end) where start and end are ST_Point's. Returns and ST_Line geometry representing the great circle.

### CODE REVIEW

**Comment by rafatower** [comment]
@andrewxhill  I'm ok with adding new functions and releasing that for you but please, would you mind fixing the tests before?

**Comment by stuartlynn** [comment]
Hey @rafatower Happy to sorry, fixing the tests has been on my todo list for ages.

**Comment by jgoizueta** [comment]
Remaining test problems are same as in master now

**Comment by stuartlynn** [comment]
Awesome thanks. This will be helpful reference for future functions as well. Appreciate it!

**Pull request merged**
