### PR TITLE
Include and aggregate _vovw_count column to count aggregated features

### PR DESCRIPTION
**Pull request by iriberri**
Closes https://github.com/CartoDB/cartodb-postgresql/issues/226

cc @jgoizueta

### CODE REVIEW

**Comment by jgoizueta** [comment]
👍

**Comment by iriberri** [comment]
Hey @ethervoid could you take a look? :-)

**Comment by ethervoid** [comment]
Despite I don't know much about how it works, it looks good to me

**Comment by jgoizueta** [comment]
The *ugly* `_vovw_count` name has been chosen because all internal details related to overviews are named with a `_vovw_` prefix (the underscore to avoid collision with user identifiers, the vovw meaning "vector overviews").

The columns counts the number of features aggregated (clustered?)  into a single overview feature.

Any suggestion to change this name to something nicer?

cc @javisantana

**Comment by javisantana** [comment]
`point_count` would be better but please, don't use obfuscated names

**Comment by javisantana** [comment]
there is one thing, what happen is there is already a column `_vovw_count` ? (or whatever is the name)

**Comment by jgoizueta** [comment]
Currently, if there's an existing `_vovw_count` we expect it to comply with our requirements (be a numeric  column with constant value 1), similarly to what we do with `cartodb`, `the_geom`.

For tables the `_vovw` prefix prevents collision with user tables because we don't allow user tables' names to start with underscore, but that's possible for user columns, sadly.

If we use `point_count` likehood of collision would be much higher. Also we may eventually have overviews por polygons...

What about  `_feature_count`?

**Comment by javisantana** [comment]
sounds good for me

**Comment by iriberri** [comment]
Sounds good to me too. Renamed :+1:.

**Comment by jgoizueta** [comment]
:+1:

**Pull request merged**
