### PR TITLE
CDB_Densify & CDB_TINmap

### PR DESCRIPTION
**Pull request by AbelVM**
**CDB_Densify** is an Iterative densification of a set of points using Delaunay triangulation, the new points have as assigned value the average value of the 3 vertex of the cell (centroid)

> @param geomin - array of geometries (points)
> 
> @param colin - array of numeric values in that points
> 
> @param iterations - integer, number of iterations
> 
> **Returns:** TABLE(geomout geometry, colout numeric)

As a side function, **CDB_TINmap** generates a pseudo contour map using the same logic

### CODE REVIEW

**Comment by AbelVM** [comment]
Real life example, with 3 iterations

https://team.cartodb.com/u/abel/viz/08655476-16b5-11e6-9826-0e3ff518bd15/embed_map

**Comment by AbelVM** [comment]
CDB_TINmap test, 3 iterations
https://team.cartodb.com/u/abel/viz/f35f0a90-1781-11e6-a32d-0ecd1babdde5/map

**Comment by ohasselblad** [comment]
@AbelVM, maybe this should go into [crankshaft](https://github.com/CartoDB/crankshaft) (research's postgres analysis extension) instead? cc @stuartlynn

**Comment by AbelVM** [comment]
Closed by https://github.com/CartoDB/crankshaft/pull/90

**Pull request closed without merging**
