### PR TITLE
Remove schema triggers

### PR DESCRIPTION
**Pull request by zenitraM**
:bomb: 

schema_triggers are required for installation of the extension, but CartoDB does not use them at all.

Removing them ensures:
- support for PostgreSQL 9.5 (currently absent)
- less headaches for everyone

### CODE REVIEW

**Comment by pnorman** [comment]
`.travis.yml` and `doc/README.md` still reference schema triggers

**Comment by zenitraM** [comment]
@rafatower can you take a look? :angel:

**Comment by rafatower** [comment]
:fire: IMHO the right decision.

cc/ @rochoa to let him know.

**Comment by zenitraM** [comment]
Ping - shall we merge this and release a new version?

**Comment by rochoa** [comment]
Let's do it!

We will have to update CartoDB's documentation about how to install it: https://github.com/CartoDB/cartodb/blob/f6dc063a515753619431977600e9219125628e42/doc/manual/source/install.rst#postgresql

**Comment by zenitraM** [comment]
@rochoa adding that on the CartoDB PR - https://github.com/CartoDB/cartodb/pull/6438 :)

**Comment by rochoa** [comment]
:muscle:

**Pull request merged**
