### PR TITLE
Add some extra fields to cdb_analysis_catalog table

### LINKED ISSUE #265: CDB_AnalysisCatalog should allow to store error messages for nodes
So it's easier to share error messages from different applications operating it.

### PR DESCRIPTION
**Pull request by rochoa**
Track user, error_message for failures, and last entity modifying the node.

Closes #265.

### CODE REVIEW

**Comment by rochoa** [comment]
cc @luisbosque @zenitraM @rafatower 

As we don't have upgrade/downgrade paths in this extension, do you know a better way to add columns to an existing table without dropping the table?

**Comment by zenitraM** [comment]
Could work - only thing I'm worried about is the NOTICEs we will get on every extension upgrade from now on.

**Comment by rochoa** [comment]
Let me try to fix that :-).

**Comment by rafatower** [comment]
I don't think it can be done much better, so OK.

**Pull request merged**
