### PR TITLE
grant usage on cartodb_id sequence when sharing read write

### LINKED ISSUE #321: Sharing a table read-write doesn't give access to sequences
**STR**
- Share a table RW with another user in the organization
- As the second user, execute an INSERT without specifying PK: `INSERT INTO owner.untitled_table (name) VALUES ('a')`

Error: `permission denied for sequence untitled_table_cartodb_id_seq0`

We should give sequence access as well in https://github.com/CartoDB/cartodb-postgresql/blob/8131887204e76722a2ebda01b0ab5acee7abc911/scripts-available/CDB_Organizations.sql#L108

### PR DESCRIPTION
**Pull request by alrocar**
Closes #321

### CODE REVIEW

**Comment by dgaubert** [comment]
Please, add someone of @CartoDB/engine as a reviewer.

**Comment by alrocar** [comment]
@dgaubert I added you :P let me know if you are available for CR or reassign to someone else, please

Thanks :)

**Comment by dgaubert** [comment]
Hey, I'm late to the party. Sorry about that. LGTM.

**Comment by alrocar** [comment]
Hey @dgaubert @oleurud , this was merged 3 months ago xDD, maybe you are looking for this PR -> https://github.com/CartoDB/cartodb-postgresql/pull/330

**Comment by oleurud** [comment]
Thanks xD

**Pull request merged**
