### PR TITLE
adding equal interval function for consistency

### PR DESCRIPTION
**Pull request by ohasselblad**
@javisantana 

let me know if you want to add control like `breaks > 0` and stuff like that

### CODE REVIEW

**Comment by ohasselblad** [comment]
@stuartlynn would you mind doing a code review of this one too?

**Comment by ohasselblad** [comment]
@rochoa, would you mind doing a CR for this?

**Comment by rochoa** [comment]
LGTM :+1:

**Comment by ohasselblad** [comment]
super, thanks :) :tomato:

**Pull request merged**
